### ISSUE TITLE
opensuse packages overwriting mirrorsorcerer magic? I am confuse.

### ISSUE THREAD

**Issue by pallaswept** [Firstyear/mirrorsorcerer#10]
Related to #9, I was recently in YaST cleaning up a repo I'd added to test a package, and noticed that everything there was still pointed at cdn.opensuse.org, which is weird, because I'd mirrorsorcerer'ed that sucka and it was meant to be pointed at mc-au.o.o.

I ran `sudo mirrorsorcerer -x` again for good measure, and it did all the changes, and `sudo zypper lr -d` showed that I was using mirrorcache-au, but looking again, YaST disagreed. Everything was pointed at cdn.opensuse.org.

So I went, screw this, I'll change it in YaST manually..... Edit, paste, edit, paste, repeat...... Which went fine, and then refreshing it [ highlighted this super fun and scary warning ](https://github.com/openSUSE/openSUSE-repos/issues/40) so I ditched all the GPG keys and started over.

I did a `sudo zypper refresh` and got a fresh GPG key....which as far as I can tell is the same exact key that I was warned about.... but since it's coming from your server I trusted it and moved along (I dunno, you've got a truthworthy face or something 😄  ....anyway I've been using your mirror for months so if you're hacking me that ship sailed long ago hahaha)

Then I went to do `sudo zypper dup` and got an error that the repo already existed for` cdn.opensuse.org`. It's like it's unkillable. Then I realised, it's that package I mentioned in #9. It installs a package that installs a service that creates the repos every time. So even though mirrorsorcerer is editing the content of /etc/zypp/repos.d, it's just being overwritten by their service which resides in `/usr/share/zypp/local/service/openSUSE`

I've nuked it all for now and gone manual, but it's really not clear what I should be doing here. The official docs say to use download.opensuse.org, the packages on opensuse.org make everything point to cdn.opensuse.org,  generating a "don't do this you're being hacked' message,  mirrorsorcerer makes it say it's using mc-au.o.o, but then it actually doesn't, unless I delete a bunch of stuff and let mirrorsorcerer do, yknow, sorcery.... I'm baffled, honestly.

Should mirrorsorcerer be modifying the services from the packages over there (ie in `/usr/share/zypp/local/service/openSUSE/repoindex.xml`) as well as or in alternative to editing the files in `repos.d`? Should those packages just be avoided? Should mirrorsorcerer be a package of it's own like theirs with a dependency excluding those packages? Should we just manually manage it with the help of mirrorsorcerer (like what I'm doing now)? 

I am totally bamboozled as to what is the right way to roll here. I'm not even sure what part of it is wrong, it is entirely possible that it is entirely pilot error..... I just know nothing works as it says on any of the tins 🥲

**Comment by Firstyear** [comment]
That sounds like a pretty major bug in the cdn release process. I'll get it raised.

**Comment by pallaswept** [comment]
> That sounds like a pretty major bug in the cdn release process. I'll get it raised.

Yell out if I can help in any way. Obviously I'm underqualified (my SuSE accreds are decades expired) but I have time to spare on it if you need it.

**Comment by Firstyear** [comment]
Is there an easy set of copy-paste steps we can use to reproduce in a container or something? That would help a lot. Or even a fresh installed machine.

**Comment by pallaswept** [comment]
> Is there an easy set of copy-paste steps we can use to reproduce in a container or something? That would help a lot. Or even a fresh installed machine.

I reckon you could probably do it with the live ISO image in a VM if that's convenient? It installs out of the box with download.opensuse.org, those packages change it to cdn.opensuse.org, and you know what mirrorsorcerer does.

I just gave it a whirl, booted the live image, it's using download.o.o, but `zypper lr -d` said no repos were installed. Installed the `openSUSE-repos-Tumbleweed` package and now it's using cdn.o.o. I tried a refresh, but didn't get the warning about the cert though, probably since it never actually installed the ones from download.o.o. I guess to get that error you'd have to actually install it so the repos get set up properly?

**Comment by Firstyear** [comment]
@pallaswept I can't seem to reproduce? Can you show me the output of:

```
rpm -qf /usr/share/zypp/local/service/openSUSE
```

Thanks!

**Comment by pallaswept** [comment]
```
> rpm -qf /usr/share/zypp/local/service/openSUSE
openSUSE-repos-Tumbleweed-20230810.a7534f6-1.1.x86_64
```

In reality, I nuked that dir so it'd stop forcing cdn.o.o on me 😆 
```
> ls /usr/share/zypp/local/service/openSUSE
ls: cannot access '/usr/share/zypp/local/service/openSUSE': No such file or directory
```

**Comment by lkocman** [comment]
[just remove openSUSE-repos details in https://github.com/openSUSE/openSUSE-repos#restoring-original-distribution-repositories](https://github.com/openSUSE/openSUSE-repos#restoring-original-distribution-repositories) or https://news.opensuse.org/2023/07/31/try-out-cdn-with-opensuse-repos/

This package is not really installed by default with exception I believe Aeon. I blame user in this particular case. If mirrorsorcerer is packaged, then I suggest to set confict with openSUSE-repos package.

**Comment by pallaswept** [comment]
> This package is not really installed by default with exception I believe Aeon. I blame user in this particular case.

The packages were recommended to me to be installed by YaST Software during an update. I didn't install them of my own accord just because they looked interesting, I installed them because the OS directly told me to.

**Comment by pallaswept** [comment]
> https://news.opensuse.org/2023/07/31/try-out-cdn-with-opensuse-repos/
>  I blame user in this particular case.

The irony in this pair of quotes directly following each other is so thick you couldn't cut it with a chainsaw. You literally link a document on the OS's official website that says "Try this feature with this package", a document which you wrote, the official package manager recommends the user install said package, the user does as he's been told (and unknowingly invited to do on that blog), finds a problem it causes with another app, and you call it user error. That's incorrect. This isn't user error. A user doing what his OS tells him to do isn't user error. It's OS error.

**Comment by pallaswept** [comment]
```
> sudo zypper install-new-recommends

Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 3 NEW packages are going to be installed:
  openSUSE-repos-MicroOS-NVIDIA openSUSE-repos-Tumbleweed openSUSE-repos-Tumbleweed-NVIDIA

3 new packages to install.

```
Are we still calling this user error?

**Comment by pallaswept** [comment]
![image](https://github.com/Firstyear/mirrorsorcerer/assets/132128962/fceb9333-a216-4ff1-a84a-d8e48e5e5473)
How about now?

**Comment by pallaswept** [comment]
Here's the revision where it was added: https://build.opensuse.org/package/view_file/openSUSE:Factory/000release-packages/openSUSE-release.spec?rev=2425

**Comment by Firstyear** [comment]
> This package is not really installed by default with exception I believe Aeon. I blame user in this particular case. If mirrorsorcerer is packaged, then I suggest to set confict with openSUSE-repos package.

mirrorsorcerer has already been updated to fix this, but it means any future changes of the repos package will probably break this again, so I'll add the conflicts to the package. 

@lkocman we should never blame the user when it's something we did. It is offensive to our users. In this case it's because there is a recommends/suggests that automatically installs. Let's do better in future.

**Comment by Firstyear** [comment]
@pallaswept I have submitted the fixes to OBS, sorry for the delay. I've been moving house and lots going on.

**Comment by pallaswept** [comment]
> @pallaswept I have submitted the fixes to OBS, sorry for the delay. I've been moving house and lots going on.

Please, no need to apologise, I don't have you on the clock here, you're doing me a favour - take your time dude! Moving house is the toughest, hang in there! I hope the new pad is great.



> we should never blame the user when it's something we did

Don't get me wrong, I make user errors _plenty_ often. It wouldn't take long to find a quote of me confessing to goofing up, in fact I just scrolled up and noticed my OP said:

> it is entirely possible that it is entirely pilot error

Having looked into it, I don't think this is one of them though. Having been accused of user error my first reaction is to go "well dummy you better figure out what you did wrong so you don't do it again some time" and doing so led me to conclude that OpenSUSE, at the present moment, comes with one set of repos, and is configured to immediately tell the user to replace them with another set, and I did so, and it's not user error, it's busted out of the tin. 

It's not so much that I'm offended, but I do have an obsession with fixing things, and fixing them properly - especially when it comes to openSUSE because I have a long professional history with the organisation leading back to the days when I started out my career as a Novell guy doing some work with Sun on the side, so this new linux that Novell were pouring money, effort and my hours into, was kinda my baby for a long time. I might be retired now, but as an end-user, much distrohopping landed me on opensuse through its own merits, I really really like it and TW is the bees knees, and I dig the new CDN and I dig mirrorsorcerer and I just want see it all work together nicely. If the conclusion to an issue like this is to blame the user then these excellent bits of software never get fixed up such that they can coexist happily and that isn't what I want for any of the parties involved. 

That's my real issue with falsely blaming the user - it means the cool software, which in this case I have a bit of heart invested into, stays broken. 

On that topic of fixing things up, I guess that for the time being, adding a `conflicts` to MS is a good measure to take, to avoid problems like I encountered... but having RTFMd about RIS through the links provided above, one of the excellent parts of this is that there is a single line of text in a configuration file, where all the sources of the packages is defined - that being `disturl` in *repoindex.xml. To quote the news article above:

> Making a change like switching users to CDN takes a one-line change in the service template. 

It strikes me that MS could function, rather than, or perhaps in addition to, just by altering several individual entries in zypp.conf and zypp.d files, by altering that `disturl` entry to point at the fastest mirror. That way, there would be no need for a conflict between the packages and they could all live happily together, and utilise the featureset of the new infrastructure to whatever is best for each end-user's machine. I'd probably call that an FR and I'm not sure if it would be a good idea or not but it does seem that it might be a way to have our cake and eat it too.

**Comment by Firstyear** [comment]
Well generally even without MS, this is a bug in opensuse because it will blow away custom repo setups like I have at home without MS.

So I think this needs to be fixed @lkocman

**Comment by pallaswept** [comment]
> custom repo setups like I have at home without MS.

You don't use MS? What a noob! ;)

> So I think this needs to be fixed

I agree. But I hope in a cool, "have our cake and eat it too" kind of way where we can have the official servers, AND the new cool CDN, AND our weird custom setups, living together harmoniously.

**Comment by Firstyear** [comment]
Ahahahah. Yeah, I actually run a copy of https://github.com/Firstyear/opensuse-proxy-cache/ inside my home network, and I manually configure all my machines to point through that. I created mirrorsorcerer to help other people though, since not everyone has been as involved in opensuse mirroring. 

> I agree. But I hope in a cool, "have our cake and eat it too" kind of way where we can have the official servers, AND the new cool CDN, AND our weird custom setups, living together harmoniously.

Yeah, I think the rollout of the new cdn has been a bit messy, and it does raise some questions about the future of the existing mirror systems. I will certainly continue to run my AU/JP mirrors though, since I know some people prefer them as they are the fastest mirrors in both regions.

**Comment by pallaswept** [comment]
After today's sudo zypper dup, I opened YaST to put back the themes I choose (I hate how it overwites my theming with openSUSE branding every few weeks!! Sure, update the package, but don't set it as my preference. GRR.)

I was met with this screen before I touched anything:

![image](https://github.com/Firstyear/mirrorsorcerer/assets/132128962/59503578-b181-4f78-bbb7-bdc46839ceb1)

There's absolutely no way that you can call this user error any more @lkocman , I literally didn't even interact with it, it just started installing repo packages all by itself before the window was even drawn for me to click on it.

**Comment by pallaswept** [comment]
> I blame user in this particular case

Quick to blame but completely fail to apologise when you're wrong. I demand better.

**Comment by Firstyear** [comment]
@pallaswept No need to be so hostile, I know it's frustrating but it's uncalled for.

**Comment by pallaswept** [comment]
Was it not factual and true? I'm not being hostile, I'm being defensive; he's being hostile.

It's not fair to place false blame on somebody and then just turn your back on them and ignore them, it's damned rude and you're damned right it's 'called for' to say it's not good enough and to demand better. Censoring it is just wrong, too.

It's not just 'frustrating', it's a crappy way to treat a human being. He wouldn't walk up to me in the street and point at me and say "It's your fault" and then just walk off in silence as he's proven wrong, but he'll do it online. It ain't right.
