### ISSUE TITLE
New mirrorcache domain for Brazil

### ISSUE THREAD

**Issue by alexandrevicenzi** [Firstyear/mirrorsorcerer#5]
Hi,

There's a new domain for BR mirrorcache, it is mirrorcache-br.opensuse.org, this follows the official patterns.
The domain cache.opensuse.net.br won't be removed anytime soon, but it's also not official.

I wonder if there are any latency differences between both domains, as our non-official is in Cloudflare and the other in openSUSE DNS.

**Comment by Firstyear** [comment]
Having a quick look it appears that https://mirrorcache-br.opensuse.org is broken? Both http and https. I'm going to put https in the pool.json though.

**Comment by alexandrevicenzi** [comment]
It works for me, what issues do you have?

**Comment by Firstyear** [comment]
It never loads at all, just hangs forever.

**Comment by alexandrevicenzi** [comment]
Intriguing, we have a monitor in place, see https://status.opensuse.net.br/, but the ping happens from Brazil. The domain is known to work in LATAM and EMEA.

The domain https://cache.opensuse.net.br/ points to the same machine, so if https://mirrorcache-br.opensuse.org/ does not work, it is very likely a DNS issue.

opensuse.org uses its own DNS, while opensuse.net.br uses Cloudflare.

**Comment by alexandrevicenzi** [comment]
Andrii pointed out that could be IPv6 related, as the machine does not have IPv6 yet, and on CF we have a proxy that gives IPv6.

```
an@localhost:~> curl -4I http://mirrorcache-br.opensuse.org/
HTTP/1.1 200 OK

an@localhost:~> curl -6I http://mirrorcache-br.opensuse.org/
curl: (7) Couldn't connect to server

an@localhost:~> ccurl -6I http://cache.opensuse.net.br/
HTTP/1.1 200 OK
```

**Comment by Firstyear** [comment]
worked it out, it's a network transport issue from where I was testing, I've fixed the mirror defs now.
