### ISSUE TITLE
Two mirrorcache instances in Brazil

### ISSUE THREAD

**Issue by alexandrevicenzi** [Firstyear/mirrorsorcerer#6]
Hi,

This relates to [this comment](https://www.reddit.com/r/openSUSE/comments/104bu6r/is_it_possible_for_a_user_to_ban_the/) on Reddit.

Brazil has two mirrorcache instances:

https://mirrorcache-br.opensuse.org/
https://mirrorcache-br-2.opensuse.org/

We do have downtimes with mirrorcache in Brazil, but never both at the same time.

Perhaps mirrorsorcerer should check if the given mirrorcache instance is UP before selecting it.

**Comment by alexandrevicenzi** [comment]
For some context, mirrorcache-br was down for a few days due to issues with our hosting provider, the problem is already fixed. Meanwhile, mirrorcache-br-2 was up and running all the time.

**Comment by alexandrevicenzi** [comment]
Bernhard is updating DNS names.

Route to both if both are UP, the preferred way to use it:

https://mirrorcache-br.opensuse.org/

Route to each instance:

https://mirrorcache-br-1.opensuse.org/
https://mirrorcache-br-2.opensuse.org/

Once the changes are completed, I think there's no need to add instance URLs.

**Comment by Firstyear** [comment]
Actually in a future update we are going to migrate the current pool to "undo" the changes since zypper now does geoip itself. 

So it's good to know about the extra instances so we can "undo" changes that may have been done manually to them.
