### ISSUE TITLE
Weird update behavior on Tumbleweed

### ISSUE THREAD

**Issue by Freemason-12** [Firstyear/mirrorsorcerer#7]
When I run `sudo zypper dup` it now stopped showing package updates as frequently as it was before, also it gives me this message:
```
Warning: Repository 'openSUSE:Tumbleweed' metadata expired since 2023-03-24 16:25:41 +06.

    Warning: Repository metadata expired: Check if 'autorefresh' is turned on (zypper lr), otherwise
    manualy refresh the repository (zypper ref). If this does not solve the issue, it could be that
    you are using a broken mirror or the server has actually discontinued to support the repository.
```
These warnings weren't there before I installed mirrorsorcerer

But when I run `sudo zypper ref` it sometimes refreshes *some* of the mirrors (mostly opensuse updates ones) but apart from that nothing changes and warning still stays there

When I run `sudo zypper up` it shows this:
`The following 102 package updates will NOT be installed: <packages...>`

I'm a bit worried that this software crippled zypper to some degree, is all of this OK?

**Comment by Firstyear** [comment]
It hasn't crippled zypper - in fact all the mirrors we "swap in" are official mirrors that are automatically redirected to via the geoip service.

You will also find in the /etc/zypper/repos.d/ folder files listed as ".msbak". These are the original files if you want to restore them. Just `mv filename.msbak filename`. 

To diagnose this I'll need to see the output of "zypper lr". But most likely this is *not* a mirrorsorcerer issue but something else.

**Comment by Freemason-12** [comment]
ok, here's an output of `zypper lr`
```
#  | Alias                                | Name                        | Enabled | GPG Check | Refresh
---+--------------------------------------+-----------------------------+---------+-----------+--------
 1 | M17N:fonts                           | M17N:fonts                  | Yes     | (r ) Yes  | No
 2 | download.opensuse.org-non-oss        | Main Repository (NON-OSS)   | Yes     | (r ) Yes  | Yes
 3 | download.opensuse.org-oss            | Main Repository (OSS)       | Yes     | (r ) Yes  | Yes
 4 | download.opensuse.org-tumbleweed     | Main Update Repository      | Yes     | (r ) Yes  | Yes
 5 | home_Aptrug                          | home:Aptrug (openSUSE_Tum-> | No      | ----      | ----
 6 | home_FrankyU2                        | home:FrankyU2 (openSUSE_T-> | No      | ----      | ----
 7 | home_bjoernv                         | home:bjoernv (openSUSE_Tu-> | No      | ----      | ----
 8 | home_favogt_symbolictw               | -Bsymbolic-functions (sta-> | No      | ----      | ----
 9 | home_munix9                          | munix9's Home Project (op-> | Yes     | (r ) Yes  | No
11 | https-download.opensuse.org-5ddeda83 | openSUSE:Tumbleweed         | Yes     | (r ) Yes  | Yes
10 | https-download.opensuse.org-3938bce6 | home:ecsos                  | No      | ----      | ----
12 | mozilla                              | mozilla                     | Yes     | (r ) Yes  | Yes
13 | packman                              | Packman                     | Yes     | (r ) Yes  | Yes
14 | repo-debug                           | openSUSE-Tumbleweed-Debug   | No      | ----      | ----
15 | repo-source                          | openSUSE-Tumbleweed-Source  | No      | ----      | ----
16 | sublime-text                         | Sublime Text - x86_64 - S-> | Yes     | (r ) Yes  | Yes
17 | vivaldi                              | vivaldi                     | Yes     | (r ) Yes  | Yes
```

**Comment by Firstyear** [comment]
See how m17n fonts and home_munix9 in the "refresh" column are both "no"? That means those two wont auto refresh their metadata.

You can change it with "zypper mr -f <name of repo>" to enable the refresh to happen "automatically" which should clear the warning.

Else you can do "zypper ref --force"  as needed. Does that help?

**Comment by Freemason-12** [comment]
I enabled autorefresh to all of my enabled repos as you requested through Yast, after that I ran `zypper lr` which shows all enabled repos with "autorefresh" column set to "yes"

Then I ran `zypper ref --force` and then `zypper dup`

The warning is still there for some reason

**Comment by Firstyear** [comment]
`11 | https-download.opensuse.org-5ddeda83 | openSUSE:Tumbleweed         | Yes     | (r ) Yes  | Yes`
That's an odd looking repo line though.

Can you find the /etc/zypp/repos.d file that contains that value and provide it's content here?

**Comment by Freemason-12** [comment]
here are the contents of `/etc/zypp/repos.d/https-download.opensuse.org-5ddeda83.repo`
```[https-download.opensuse.org-5ddeda83]
name=openSUSE:Tumbleweed
enabled=1
autorefresh=1
baseurl=https://mirrorcache.opensuse.org/repositories/openSUSE:/Tumbleweed/standard/
type=rpm-md
keeppackages=0
```

**Comment by Firstyear** [comment]
That repo is valid and working but seems to only have a kernel build present. Everything I'm seeing says it's working. Can you do:

```
zypper -vv ref --force https-download.opensuse.org-5ddeda83
```

And post all the output here?

**Comment by Freemason-12** [comment]
here is the output of your command
```
Verbosity: 3
Non-option program arguments: 'https-download.opensuse.org-5ddeda83' 
Initializing Target
Specified repositories: https-download.opensuse.org-5ddeda83 
Forcing raw metadata refresh
Retrieving: https://mirrorcache.opensuse.org/repositories/openSUSE:/Tumbleweed/standard[done (413 B/s)]
Retrieving: https://mirrorcache.opensuse.org/repositories/openSUSE:/Tumbleweed/standa[done (1.6 KiB/s)]
Retrieving: https://mirrorcache.opensuse.org/repositories/openSUSE:/Tumbleweed/standa[done (2.7 KiB/s)]
  Repository:       openSUSE:Tumbleweed
  Key Fingerprint:  AD48 5664 E901 B867 051A B15F 35A2 F86E 29B7 00A4
  Key Name:         openSUSE Project Signing Key <opensuse@opensuse.org>
  Key Algorithm:    RSA 4096
  Key Created:      Mon 20 Jun 2022 08:03:14 PM +06
  Key Expires:      Fri 19 Jun 2026 08:03:14 PM +06
  Rpm Name:         gpg-pubkey-29b700a4-62b07e22
Retrieving repository 'openSUSE:Tumbleweed' metadata ............................................[done]
Forcing building of repository cache
Building repository 'openSUSE:Tumbleweed' cache .................................................[done]
Specified repositories have been refreshed.
```

**Comment by Firstyear** [comment]
That all looks correct and valid to me. I think there are no issues being caused by mirrorsorcerer here, so I'm not sure I can help you further sorry. :(

**Comment by andrii-suse** [comment]
This problem might be caused by mirrorcache not correctly handling linked folder: download.opensuse.org actually redirects /repositories/openSUSE:/Tumbleweed/standard to /tumbleweed/repo/oss/ . mirrorcache.opensuse.org should do the same, but it doesn't
Long story short - until mirrorcache is fixed you can replace `/repositories/openSUSE:/Tumbleweed/standard` with `/tumbleweed/repo/oss/` in your repo files. 
Or better check if you have `/tumbleweed/repo/oss/` already in another .repo file and just delete/disable that problem repo  `https-download.opensuse.org-5ddeda83` using `zypper rr https-download.opensuse.org-5ddeda83`

**Comment by Firstyear** [comment]
Thanks for the fantastic answer @andrii-suse !

**Comment by Freemason-12** [comment]
> This problem might be caused by mirrorcache not correctly handling linked folder: download.opensuse.org actually redirects /repositories/openSUSE:/Tumbleweed/standard to /tumbleweed/repo/oss/ . mirrorcache.oopensuse.org should do the same, but it doesn't Long story short - until mirrorcache is fixed you can replace `/repositories/openSUSE:/Tumbleweed/standard` with `/tumbleweed/repo/oss/` in your repo files. Or better check if you have `/tumbleweed/repo/oss/` already in another .repo file and just delete/disable that problem repo `https-download.opensuse.org-5ddeda83` using `zypper rr https-download.opensuse.org-5ddeda83`

I have this repo on my repos.d (it's not the problem repo though):
```
[download.opensuse.org-oss]
name=Main Repository (OSS)
enabled=1
autorefresh=1
baseurl=https://mirrorcache.opensuse.org/tumbleweed/repo/oss/
path=/
type=rpm-md
keeppackages=0
```
Is this enough, or do I have to go ahead and manually rename the problem file?

**Comment by Firstyear** [comment]
You can just disable the problem repo with: `zypper mr -d <name of repo>`. That will disable it.

**Comment by Freemason-12** [comment]
You mean that the problem repo mentioned is unneeded?

**Comment by Firstyear** [comment]
Since it's the same as the tumbleweed/repo/oss repo, then yes from my reading of what @andrii-suse said you don't need the problem repo.

**Comment by Freemason-12** [comment]
For some reason, when I open that problem repo link to the browser, it open fine without redirecting. Should I be concerned about this?

**Comment by Freemason-12** [comment]
Oh wait, I was taking the mirrorcache URL, sorry, yes you are right

**Comment by Firstyear** [comment]
No, it's a difference between mirrorcache/zypper internall. Your browser is handling it correctly.

Remember also this isn't deleting the repo, just disabling it.

Afterwards you should do "zypper ref --force" followed by "zypper dup --allow-vendor-change" to ensure packages get updated to their new/correct source repos (else you will have other issues).

**Comment by Freemason-12** [comment]
There also another concern, when i look at mirrorcache repo (`https://mirrorcache.opensuse.org/tumbleweed/repo/oss/`), I see that it's been last modified year ago, compared to the official one (`https://download.opensuse.org/tumbleweed/repo/oss/`) is it fine?

**Comment by andrii-suse** [comment]
ah, it is fine. I may lag timestamps on files or show a little outdated files when human is browsing. 
But for zypper it works reliably.
I must improve browsing though.
