### ISSUE TITLE
Option to return to default repo links

### ISSUE THREAD

**Issue by casparvitch** [Firstyear/mirrorsorcerer#8]
Occasionally I have issues with the mirrorcache servers/urls, but 'regular' download.opensuse.org works fine.
I have been manually editing the repo urls.

It would be great if there was an option in mirrorsorcerer to  do this for me, e.g. `mirrorsorcerer -g -x`, 'g' for generic, as 'd' is taken for daemon.

Cheers!

**Comment by Firstyear** [comment]
@casparvitch Fixed in main, added the -u flag to restore -u pstream mirrors. Will release to opensuse TW asap.

**Comment by casparvitch** [comment]
Works perfectly, cheers!
